### ISSUE TITLE
Airdrops for SPL tokens

### ISSUE THREAD

**Issue by armaniferrante** [paul-schaaf/spl-token-ui#46]
**Is your feature request related to a problem? Please describe.**

I would like the ability to fund a wallet for an SPL token on devnet or localhost, given that I'm not the mint authority, so that I can use apps on Devnet requiring particular tokens.

**Describe the solution you'd like**

Extending either the current SOL airdrop mechanism spl token editor could work. Given this is mostly just for testing (for my use case at least), the easiest way might be to hard code a private key representing the mint authority into the app, but I don't have a preference on the implementation details.

**Comment by paul-schaaf** [comment]
@armaniferrante 
How about writing a little on-chain program whose Program Derived Address can be assigned to a token as the mint authority?
It could a) mint [hardcoded or user supplied] number of tokens to the regular user
b) if the number of tokens is hardcoded for normal requests, it could also accept an admin key which may mint any amount

**Comment by armaniferrante** [comment]
@paul-schaaf your solution sounds great.

**Comment by paul-schaaf** [comment]
@armaniferrante does this look good to you concerning functionality?
https://github.com/paul-schaaf/spl-token-faucet/blob/main/src/program/src/instruction.rs

**Comment by armaniferrante** [comment]
LGTM. Do you need a nonce for the program-derived address?

**Comment by paul-schaaf** [comment]
I don't think so. You think I might need it for something? @armaniferrante

**Comment by armaniferrante** [comment]
I figured you'd need it for generating program signatures for mint and/or transfer instructions. Users shouldn't need it for anything.

**Comment by paul-schaaf** [comment]
ah yea Ill need to invoke_signed but since Im going with a static seed, the nonce will always be the same and does not need to be saved or passed in to the ix. see: https://github.com/paul-schaaf/spl-token-faucet/blob/1cfa37f350d37a3c9a277a04adf3fff185180cd0/src/program/src/processor.rs#L45 @armaniferrante
