### ISSUE TITLE
Feature Request: Allow 64 digit array secret as secret input in forms instead of only the seed phrase

### ISSUE THREAD

**Issue by michaelhly** [paul-schaaf/spl-token-ui#9]

**Comment by paul-schaaf** [comment]
@michaelhly Are you talking about a secret key or the keypair with both keys? pls write down an example as a comment here, just so we are on the same page. 🙂

**Comment by michaelhly** [comment]
64-byte `secretKey` in the form of Uint8Array.

https://github.com/dchest/tweetnacl-js/blob/f1ec050ceae0861f34280e62498b1d3ed9c350c6/README.md#signatures

https://github.com/solana-labs/solana-web3.js/blob/43facecc4dec7b1e299b6e885c311401e82f0f0a/src/account.js#L22

This is how I get the secret key:
https://github.com/solana-labs/solana-web3.js/blob/43facecc4dec7b1e299b6e885c311401e82f0f0a/src/account.js#L40

I call:
```js
const a = Account()
const secretKey = a.secretKey().toString()
console.log(secretKey)
```

**Comment by paul-schaaf** [comment]
resolved!
